universe = vanilla
executable = /home/grads/syang75/miniconda3/bin/conda

output = training.out
error = training.err
log = training.log

# Define the arguments for each job
queue arguments from (
    run -n cloned python /public/syang75/BC-Security_/UnifiedEnv/squirRLA2C.py
    run -n cloned python /public/syang75/BC-Security_/UnifiedEnv/squirRLPPO.py
    run -n cloned python /public/syang75/BC-Security_/UnifiedEnv/squirRLDQN.py
)