universe = vanilla
executable = /home/grads/syang75/miniconda3/bin/conda

output = training.out
error = training.err
log = training.log

# Define the arguments for each job
queue arguments from (
    run -n advancedBCsec python /public/syang75/BC-Security/UnifiedEnv/A2C.py -rl dqn
    run -n advancedBCsec python /public/syang75/BC-Security/UnifiedEnv/PPO.py -rl ppo
    run -n advancedBCsec python /public/syang75/BC-Security/UnifiedEnv/DQN.py -rl a2c
)